memory:
  db_path: agent_memory.db
minecraft:
  password: ${MINECRAFT_PASSWORD}
  server_host: 64.87.37.104
  server_port: 25565
  username: AgentBot1
openai:
  api_key: ${OPENAI_API_KEY}
  model: o4-mini
